url: https://disclosures-clerk.house.gov/public_disc/financial-pdfs/{YEAR}FD.zip
db: db/database.db
years:
  - 2024
zip_path: data/zip
xml_directory: data/xml
members:
  - gottheimer
  - goldman
  - tuberville
  - pelosi
  - scott
  - franklin
  - mullin
  - green
